from="/mnt/c/Users/32664/Downloads/"
to="/mnt/d/code/py-code/cs61a/"
file="hw04-2cf46d1f8dc71ad7d8bacb4815de3044.zip"
vimfile="/mnt/d/code/shell/get.sh"

alias vimit="vim $vimfile"
alias cdfrom="cd $from"
alias cdto="cd $to"
alias mvto="mv $from$file $to"
alias mvfrom="mv $to$file $from"
alias show="find . -maxdepth 1 -name $file"
